// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OracleJwtApiFull.Data;

#nullable disable

namespace OracleJwtApiFull.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250521111108_AddWalletTable")]
    partial class AddWalletTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OracleJwtApiFull.Models.Airplane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessCapacity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BUSINESS_CAPACITY");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<int>("EconomyCapacity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ECONOMY_CAPACITY");

                    b.Property<int>("FirstClassCapacity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FIRST_CLASS_CAPACITY");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("MODEL");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("AIRPLANES", (string)null);
                });

            modelBuilder.Entity("OracleJwtApiFull.Models.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CITY");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("CODE");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("COUNTRY");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("AIRPORTS", (string)null);
                });

            modelBuilder.Entity("OracleJwtApiFull.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FLIGHT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<int>("AirplaneId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AIRPLANE_ID");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ARRIVAL_TIME");

                    b.Property<int>("AvailableBusinessSeats")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AVAILABLE_BUSINESS_SEATS");

                    b.Property<int>("AvailableEconomySeats")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AVAILABLE_ECONOMY_SEATS");

                    b.Property<int>("AvailableFirstClassSeats")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AVAILABLE_FIRST_CLASS_SEATS");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DEPARTURE_TIME");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DESTINATION_AIRPORT_ID");

                    b.Property<string>("Duration")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DURATION");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("FLIGHT_NUMBER");

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORIGIN_AIRPORT_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("FlightId");

                    b.HasIndex("AirplaneId");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex("OriginAirportId");

                    b.ToTable("FLIGHTS", (string)null);
                });

            modelBuilder.Entity("OracleJwtApiFull.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("DATE")
                        .HasColumnName("DATE_OF_BIRTH");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("GENDER");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("LAST_LOGIN");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ROLE");

                    b.HasKey("Id");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("OracleJwtApiFull.Models.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("WALLET_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletId"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("BALANCE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID");

                    b.HasKey("WalletId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("WALLETS", (string)null);
                });

            modelBuilder.Entity("OracleJwtApiFull.Models.Flight", b =>
                {
                    b.HasOne("OracleJwtApiFull.Models.Airplane", "Airplane")
                        .WithMany()
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OracleJwtApiFull.Models.Airport", "DestinationAirport")
                        .WithMany()
                        .HasForeignKey("DestinationAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OracleJwtApiFull.Models.Airport", "OriginAirport")
                        .WithMany()
                        .HasForeignKey("OriginAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airplane");

                    b.Navigation("DestinationAirport");

                    b.Navigation("OriginAirport");
                });

            modelBuilder.Entity("OracleJwtApiFull.Models.Wallet", b =>
                {
                    b.HasOne("OracleJwtApiFull.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("OracleJwtApiFull.Models.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
